package stats

import (
	"fmt"
	"io"
	"os"
	"strings"

	"github.com/charmbracelet/lipgloss"
	"github.com/charmbracelet/x/term"
	"github.com/mattn/go-isatty"
)

// renderTerminal produces the full terminal report for ds and writes it to
// w. The renderer auto-detects whether w is a TTY so output is plain ASCII
// when piped or redirected. NO_COLOR is honored automatically through the
// underlying termenv backend.
func renderTerminal(ds *DemoStats, w io.Writer, title string) error {
	if ds == nil || len(ds.Players) == 0 {
		_, err := fmt.Fprintln(w, "No statistics available")
		return err
	}

	s := newStyles(w, detectTTY(w))
	data := buildHTMLData(ds)
	width := terminalWidth(w)

	var out strings.Builder

	out.WriteString(renderHeader(s, title, data.GeneratedAt))
	out.WriteString("\n\n")
	out.WriteString(renderDemoBlock(s, data))
	out.WriteString("\n\n")

	if data.PlayerCount > 0 {
		out.WriteString(renderVerdict(s, data))
		out.WriteString("\n\n")
	}

	if scoreboard := renderScoreboard(s, data.Teams); scoreboard != "" {
		out.WriteString(renderSectionDivider(s, "SCOREBOARD", width))
		out.WriteString("\n\n")
		out.WriteString(scoreboard)
		out.WriteString("\n\n")
	}

	out.WriteString(renderSectionDivider(s, "PER-PLAYER ANALYSIS", width))
	out.WriteString("\n\n")

	cardInner := cardInnerWidth(width)
	for _, p := range data.Players {
		out.WriteString(renderPlayerCard(s, p, cardInner))
		out.WriteString("\n\n")
	}

	out.WriteString(renderFooter(s, data, width))
	out.WriteString("\n")

	_, err := io.WriteString(w, out.String())
	return err
}

func detectTTY(w io.Writer) bool {
	f, ok := w.(*os.File)
	if !ok {
		return false
	}
	return isatty.IsTerminal(f.Fd())
}

func terminalWidth(w io.Writer) int {
	f, ok := w.(*os.File)
	if !ok {
		return 100
	}
	if !isatty.IsTerminal(f.Fd()) {
		return 100
	}
	cols, _, err := term.GetSize(f.Fd())
	if err != nil || cols < 60 {
		return 100
	}
	if cols > 140 {
		return 140
	}
	return cols
}

func cardInnerWidth(width int) int {
	w := width - 4
	if w < 56 {
		w = 56
	}
	if w > 132 {
		w = 132
	}
	return w
}

func renderHeader(s *styles, title, generatedAt string) string {
	left := s.headerName.Render(title)
	right := s.header.Render(generatedAt)
	leftW := lipgloss.Width(left)
	rightW := lipgloss.Width(right)
	gap := 80 - leftW - rightW
	if gap < 2 {
		gap = 2
	}
	spacer := s.r.NewStyle().Width(gap).Render("")
	return lipgloss.JoinHorizontal(lipgloss.Top, left, spacer, right)
}

func renderDemoBlock(s *styles, d htmlData) string {
	var b strings.Builder
	b.WriteString(s.demoTitle.Render(d.DemoName))
	b.WriteString("\n")
	parts := make([]string, 0, 4)
	if d.MapName != "" {
		parts = append(parts, "Map "+s.metaCode.Render(d.MapName))
	}
	if d.GameMode != "" {
		parts = append(parts, s.metaCode.Render(d.GameMode))
	}
	if d.RoundCount > 0 {
		parts = append(parts, fmt.Sprintf("%d rounds", d.RoundCount))
	}
	parts = append(parts, fmt.Sprintf("%d players", d.PlayerCount))
	b.WriteString(s.meta.Render(strings.Join(parts, " · ")))
	return b.String()
}

func renderVerdict(s *styles, d htmlData) string {
	countStyle := s.verdictClean
	if d.FlaggedCount > 0 {
		countStyle = s.verdictFlag
	}
	first := countStyle.Render(fmt.Sprintf("%d", d.FlaggedCount)) +
		s.verdict.Render(fmt.Sprintf(" of %d players flagged.", d.PlayerCount))

	detail := fmt.Sprintf(
		"Threshold for auto-flag is 50%%. Highest %.1f%% (%s), lowest %.1f%% (%s).",
		d.HighestLikelihood, d.HighestName, d.LowestLikelihood, d.LowestName,
	)
	return first + "\n" + s.verdictDetail.Render(detail)
}

func renderSectionDivider(s *styles, label string, width int) string {
	title := s.sectionTitle.Render(label)
	titleW := lipgloss.Width(title)
	fill := width - titleW - 4
	if fill < 4 {
		fill = 4
	}
	dashes := s.header.Render(strings.Repeat("─", fill))
	if !s.isTTY {
		dashes = s.header.Render(strings.Repeat("-", fill))
	}
	return s.header.Render("── ") + title + " " + dashes
}

func renderFooter(s *styles, d htmlData, width int) string {
	left := "Generated by demo-anticheat"
	right := fmt.Sprintf("%d players · %d metrics", d.PlayerCount, d.MetricCount)
	gap := width - len(left) - len(right)
	if gap < 2 {
		gap = 2
	}
	line := left + strings.Repeat(" ", gap) + right
	return s.footer.Render(line)
}
